server:
  port: 7072

spring:
  application:
    name: product-service
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/icommerce'
    initialization-mode: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8762
